language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly" # currently points to 3.7-dev
install:
    - "pip install pytest"
    - "pip install pytest-cov"
    - "pip install coveralls"
script:
    PYTHONPATH=. py.test --cov arglog tests/
after_success:
    coveralls
